# Define workflow name.
name: MatrixOne CI

on:
  workflow_call:

jobs:
  ut-linux-x86:
    runs-on: ubuntu-latest
    name: UT Test on Ubuntu/x86      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '3'
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - run: |
          echo 'aaa';
