# Define workflow name.
name: MatrixOne CI

on:
  workflow_dispatch:

jobs:
  ut-linux-x86:
    runs-on: gugus-test
    name: UT Test on Ubuntu/x86      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '3'
          repository: matrixorigin/matrixone
          ref: main
      - run: |
          echo 'aaa';
